-- VisiSign database schema — PostgreSQL (the cloud build).
--
-- A deliberately faithful port of schema.sql. Two choices keep the repository
-- layer shared between the two backends instead of forked:
--
--   * timestamps are TEXT in 'YYYY-MM-DD HH:MM:SS' UTC form, exactly as SQLite
--     stores them, so every range filter and sort in the queries is the same
--     lexicographic string comparison on both backends;
--   * booleans are SMALLINT 0/1, so `is_active = 1` needs no translation.
--
-- Idempotent (IF NOT EXISTS throughout) and guarded by an advisory lock in the
-- driver, so several instances booting at once cannot race each other.

-- ─────────────────────────────────────────────────────────────────────────────
-- Places: a site has rooms, a room has desks.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sites (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT     NOT NULL,
  address     TEXT,
  timezone    TEXT     NOT NULL DEFAULT 'UTC',
  is_active   SMALLINT NOT NULL DEFAULT 1,
  created_at  TEXT     NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS rooms (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id     INTEGER  NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name        TEXT     NOT NULL,
  floor       TEXT,
  capacity    INTEGER  NOT NULL DEFAULT 0,
  created_at  TEXT     NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_rooms_site ON rooms(site_id);

CREATE TABLE IF NOT EXISTS desks (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id     INTEGER  NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  label       TEXT     NOT NULL,
  is_bookable SMALLINT NOT NULL DEFAULT 1,
  created_at  TEXT     NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_desks_room ON desks(room_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- People with logins. users holds auth + role; staff/admins hold role profiles.
-- guests have no login and are created on sign-in.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id      TEXT     NOT NULL UNIQUE,           -- opaque id exposed to clients
  email          TEXT     NOT NULL UNIQUE,           -- the login identifier (not necessarily an email)
  password_hash  TEXT     NOT NULL,
  full_name      TEXT     NOT NULL,
  role           TEXT     NOT NULL CHECK (role IN ('staff','admin')),
  access_level   INTEGER  NOT NULL DEFAULT 1,        -- 1=basic .. 9=superadmin
  is_active      SMALLINT NOT NULL DEFAULT 1,
  created_at     TEXT     NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at     TEXT     NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);

CREATE TABLE IF NOT EXISTS staff (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  site_id     INTEGER REFERENCES sites(id) ON DELETE SET NULL,
  department  TEXT,
  title       TEXT,
  phone       TEXT,
  photo_url   TEXT
);

CREATE TABLE IF NOT EXISTS admins (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  scope       TEXT    NOT NULL DEFAULT 'global'      -- 'global' or a site scope
);

CREATE TABLE IF NOT EXISTS guests (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id    TEXT NOT NULL UNIQUE,
  full_name    TEXT NOT NULL,
  company      TEXT,
  email        TEXT,
  phone        TEXT,
  photo_url    TEXT,
  created_at   TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_guests_name ON guests(full_name);

-- ─────────────────────────────────────────────────────────────────────────────
-- Visits: the core event table. A row is one sign-in. type distinguishes a
-- guest visit from a staff work session. Open visits have signed_out_at = NULL.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS visits (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id      TEXT NOT NULL UNIQUE,
  type           TEXT NOT NULL CHECK (type IN ('guest','staff')),
  guest_id       INTEGER REFERENCES guests(id) ON DELETE SET NULL,
  staff_user_id  INTEGER REFERENCES users(id)  ON DELETE SET NULL,
  host_user_id   INTEGER REFERENCES users(id)  ON DELETE SET NULL, -- who is hosting a guest
  host_name      TEXT,                                            -- free text fallback
  site_id        INTEGER REFERENCES sites(id) ON DELETE SET NULL,
  room_id        INTEGER REFERENCES rooms(id) ON DELETE SET NULL,
  desk_id        INTEGER REFERENCES desks(id) ON DELETE SET NULL,
  reason         TEXT,
  status         TEXT NOT NULL DEFAULT 'signed_in'
                      CHECK (status IN ('signed_in','signed_out')),
  custom_data    TEXT,                                            -- JSON blob of custom form fields
  signed_in_at   TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  signed_out_at  TEXT
);
CREATE INDEX IF NOT EXISTS idx_visits_status ON visits(status);
CREATE INDEX IF NOT EXISTS idx_visits_type   ON visits(type);
CREATE INDEX IF NOT EXISTS idx_visits_in     ON visits(signed_in_at);
CREATE INDEX IF NOT EXISTS idx_visits_staff  ON visits(staff_user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- Badges: a printable / scannable credential issued for a visit.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS badges (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id     INTEGER NOT NULL REFERENCES visits(id) ON DELETE CASCADE,
  code         TEXT    NOT NULL UNIQUE,             -- the badge serial
  qr_payload   TEXT    NOT NULL,                    -- string encoded into the QR
  issued_at    TEXT    NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  revoked_at   TEXT
);
CREATE INDEX IF NOT EXISTS idx_badges_visit ON badges(visit_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- Alerts: notifications raised by rules (e.g. visitor still on site after hours).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS alerts (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level         TEXT     NOT NULL CHECK (level IN ('info','warning','critical')),
  message       TEXT     NOT NULL,
  visit_id      INTEGER REFERENCES visits(id) ON DELETE SET NULL,
  site_id       INTEGER REFERENCES sites(id) ON DELETE SET NULL,
  is_resolved   SMALLINT NOT NULL DEFAULT 0,
  created_at    TEXT     NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  resolved_at   TEXT
);
CREATE INDEX IF NOT EXISTS idx_alerts_open ON alerts(is_resolved);

-- ─────────────────────────────────────────────────────────────────────────────
-- Logs: immutable audit trail of who did what.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS logs (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_type   TEXT NOT NULL,                       -- 'system','guest','staff','admin'
  actor_id     INTEGER,                             -- users.id or guests.id, nullable
  action       TEXT NOT NULL,                       -- e.g. 'visit.signin'
  target_table TEXT,
  target_id    INTEGER,
  detail       TEXT,                                -- JSON
  ip           TEXT,
  created_at   TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_logs_action ON logs(action);
CREATE INDEX IF NOT EXISTS idx_logs_time   ON logs(created_at);

-- ─────────────────────────────────────────────────────────────────────────────
-- Reservations: pre-check-in from a phone. A visitor picks a date + time slot
-- and fills the form ahead of time. On arrival they are checked in, which
-- creates a real visit (and badge) and links it back here.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reservations (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id      TEXT NOT NULL UNIQUE,
  full_name      TEXT NOT NULL,
  company        TEXT,
  email          TEXT,
  phone          TEXT,
  host_name      TEXT,
  reason         TEXT,
  site_id        INTEGER REFERENCES sites(id) ON DELETE SET NULL,
  reserved_date  TEXT NOT NULL,                     -- 'YYYY-MM-DD' (site-local)
  time_slot      TEXT NOT NULL,                     -- 'HH:MM' start of slot (site-local)
  status         TEXT NOT NULL DEFAULT 'reserved'
                      CHECK (status IN ('reserved','checked_in','cancelled')),
  custom_data    TEXT,                              -- JSON of extra form fields
  visit_id       INTEGER REFERENCES visits(id) ON DELETE SET NULL,
  created_at     TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  checked_in_at  TEXT
);
CREATE INDEX IF NOT EXISTS idx_res_date   ON reservations(reserved_date, time_slot);
CREATE INDEX IF NOT EXISTS idx_res_status ON reservations(status);

-- ─────────────────────────────────────────────────────────────────────────────
-- Kiosks: devices that want to run the on-site kiosk UI. A device registers
-- (status 'pending') and an administrator must accept it before it can show the
-- kiosk. Each device carries an opaque public_id (stored in the browser) and a
-- short human code the admin references to accept it.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS kiosks (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id     TEXT NOT NULL UNIQUE,          -- device id from the browser
  code          TEXT NOT NULL,                 -- short code shown on the device
  name          TEXT,
  status        TEXT NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending','accepted','revoked','rejected')),
  user_agent    TEXT,
  ip            TEXT,
  requested_at  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  accepted_at   TEXT,
  last_seen_at  TEXT
);
CREATE INDEX IF NOT EXISTS idx_kiosks_status ON kiosks(status);

-- ─────────────────────────────────────────────────────────────────────────────
-- Settings: simple key/value for tunable system config managed by admins.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS settings (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL,
  updated_at  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Print jobs: the cloud server cannot reach the label printer at reception, so
-- badge prints become a queue. The on-premise print agent (see /agent) polls
-- for queued jobs, drives the local Windows printer, and reports back.
--
-- This table exists in BOTH schemas so the agent protocol is identical whether
-- VisiSign runs in the cloud or on the reception PC.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS print_jobs (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id     TEXT NOT NULL UNIQUE,
  visit_id      INTEGER REFERENCES visits(id) ON DELETE CASCADE,
  payload       TEXT NOT NULL,                 -- JSON badge render spec
  status        TEXT NOT NULL DEFAULT 'queued'
                     CHECK (status IN ('queued','claimed','done','failed')),
  attempts      INTEGER NOT NULL DEFAULT 0,
  error         TEXT,
  agent_id      TEXT,                          -- which agent claimed it
  created_at    TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  claimed_at    TEXT,
  finished_at   TEXT
);
CREATE INDEX IF NOT EXISTS idx_print_jobs_status ON print_jobs(status, created_at);

-- ─────────────────────────────────────────────────────────────────────────────
-- Signatures: a visitor's acceptance of the terms shown at the kiosk.
--
-- This is a legal record, so it stores WHAT was agreed to, not just that
-- something was: the terms text is hashed and its version recorded, so a later
-- edit to the terms cannot silently rewrite what someone signed. The drawn
-- signature is kept as a PNG data URL alongside the visit it belongs to.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS signatures (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id      INTEGER REFERENCES visits(id) ON DELETE CASCADE,
  signer_name   TEXT NOT NULL,
  tos_version   TEXT,                       -- the terms version in force when signed
  tos_hash      TEXT,                       -- SHA-256 of the exact text agreed to
  signature_png TEXT,                       -- data: URL of the drawn signature
  ip            TEXT,
  user_agent    TEXT,
  signed_at     TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_signatures_visit ON signatures(visit_id);
